### ISSUE TITLE
Question about displaying images loaded to CAS Table

### ISSUE THREAD

**Issue by iagomez** [sassoftware/sas-viya-machine-learning#31]
Hello,

I have a question that hopefully a member from this project can help answer. 

I'm using the image action set to load and reshape some images. I borrowed the `imageShow()` function from @pepecura's Jupyter notebook `Car-Damage-Image-Analysis-for-Insurance.ipynb`

```
# define the function to display the processed image files.
def imageShow(session, casTable, imageId, nimages):
    a = session.table.fetch(sastypes=False,sortby=[{'name':'_id_'}],table=casTable,to=nimages)
    fig = plt.figure(figsize=(20, 20))
    for i in range(nimages):
        imageData = a['Fetch'].iloc[i][imageId]
        img_np = cv2.imdecode(np.fromstring( imageData, np.uint8),1)
        fig.add_subplot(1,nimages,i+1)
        plt.imshow(img_np)
        img_np[:,:,[0,2]]=img_np[:,:,[2,0]]
        plt.xticks([]), plt.yticks([])
```

**The issue** I'm having is that when I use it to display my images, they all show up overly blue:
![image](https://user-images.githubusercontent.com/2080150/36346161-70dc7538-1407-11e8-88a7-b708eed3fc29.png)

Source images are `.jpg` and if open any of them with a regular image viewer they show up with normal colors:
![image](https://user-images.githubusercontent.com/2080150/36346207-082ae7bc-1408-11e8-845c-48457fc55df9.png)

Could you please help me understand why my pictures are showing up with blue tinting or recommend a better function to display images loaded into a CAS table?

Thanks!

**Comment by milkstout** [comment]
It seems like about BGR vs RGB. Removing this line "img_np[:,:,[0,2]]=img_np[:,:,[2,0]]" would help.

**Comment by iagomez** [comment]
Hey @milkstout,

Thank you for your feedback! Your hint helped me figure it out. I moved `img_np[:,:,[0,2]]=img_np[:,:,[2,0]]` right above `plt.imshow(img_np)` and it's working now 😀

This the function that did the trick for me, in case anyone else runs into the same problem:

```
def imageShow(session, casTable, imageId, nimages):
    a = session.table.fetch(sastypes=False,sortby=[{'name':'_id_'}],table=casTable,to=nimages)
    fig = plt.figure(figsize=(20, 20))
    for i in range(nimages):
        imageData = a['Fetch'].iloc[i][imageId]
        img_np = cv2.imdecode(np.fromstring( imageData, np.uint8),1)
        fig.add_subplot(1,nimages,i+1)
        img_np[:,:,[0,2]]=img_np[:,:,[2,0]]
        plt.imshow(img_np)
        plt.xticks([]), plt.yticks([])
```

![image](https://user-images.githubusercontent.com/2080150/36399259-0a2b6a18-1599-11e8-8cbf-9c14df45815f.png)
